EOS-14706 Enhance setup scripts and cortxfscli to support NFSv3 mount
Seagate/cortx-posix pull request #294
Opened 2020-11-10 12:37 UTC by SwapnilGaonkar7

Changing doc according to changes done

Signed-off-by: Swapnil Gaonkar <754021@ssc-vm-c-0342.colo.seagate.com>

2020-11-11 17:26 UTC, sachinpunadikar approved these changes
+1

2020-11-24 07:41 UTC, s-arya requested changes

2020-11-24 07:41 UTC, s-arya commented on doc/Test_Instructions.md
> +   `cortxfscli endpoint create <fs_name> proto=nfs,secType=sys,client=1,clients=*,Squash=root_squash,access_type=RW,protocols=4,disable_acl=true`
Any specific reasons why are we saying `protocols=4` here? Should it be `protocols=3`, since for now, we only support NFS v3

2020-11-25 07:43 UTC, s-arya approved these changes

2020-11-25 07:49 UTC, merged