EOS-15291: Script to install the nodejs rpm and its dependencies.
Seagate/cortx-posix pull request #297
Opened 2020-11-30 07:28 UTC by Shreya-18

Add a script that installs the dependency modules like node and npm RPMs of specific versions.
This script can be later updated to fetch required packages for setting up the node-js server and starting it.

2020-11-30 07:45 UTC, s-arya requested changes
Looks good, few suggestions and questions.

2020-11-30 07:45 UTC, s-arya commented on scripts/nodejs_setup.sh
> +	sudo curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
Suggestion: Can we make this link as a bash global variable so that it's easy to modify in future?

2020-11-30 07:45 UTC, s-arya commented on scripts/nodejs_setup.sh
> +	                          Try updating yum."
Question: A yum update might update the whole Linux distribution, including the kernel. Can we modify this warning/message to be more specific?

2020-11-30 10:21 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +	sudo curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
Ofcourse, thanks will make it.

2020-11-30 10:22 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +	                          Try updating yum."
sure, I ll try to find out a more specific way

2020-11-30 12:00 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +	sudo curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
done

2020-11-30 12:01 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +	                          Try updating yum."
yes, updated the message with the link to other node-js source distribution

2020-12-01 05:05 UTC, SeagateChaDeepak approved these changes
LGTM +1

2020-12-01 05:05 UTC, SeagateChaDeepak commented on scripts/nodejs_setup.sh
> +   start      Start the node-js server
Start is not used currently so please remove it from usage string.

2020-12-01 05:41 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +   start      Start the node-js server
done

2020-12-01 08:32 UTC, s-arya approved these changes
LGTM, +1

2020-12-01 09:19 UTC, sachinpunadikar commented on scripts/nodejs_setup.sh
> +	*       ) usage;;
We can improve it further : 
echo "\n Invalid command/option \n";
usage;;

2020-12-01 09:36 UTC, sachinpunadikar approved these changes
A minor comment, rest all looks good

2020-12-01 10:00 UTC, Shreya-18 commented on scripts/nodejs_setup.sh
> +	*       ) usage;;
done, thanks

2020-12-01 10:26 UTC, merged