CORTX-28870: Adding the allowable list for Alex scan
Seagate/cortx-posix pull request #312
Opened 2022-02-18 13:46 UTC by venkuppu-chn

Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

2022-02-21 03:03 UTC, sachinpunadikar approved these changes
+1

2022-03-08 05:57 UTC, rahul-tripathi-git requested changes

2022-03-08 05:57 UTC, rahul-tripathi-git commented on .alexrc
> +  "allow": ["execute", "host-hostess", "remains", "reject", "traps", "invalid", "period", "invalid", "execution", "simple", "failure"]
invalid is twice in this list, please fix this.

2022-03-08 10:23 UTC, mukul-seagate11 approved these changes
looks good

2022-03-08 12:42 UTC, venkuppu-chn commented on .alexrc
> +  "allow": ["execute", "host-hostess", "remains", "reject", "traps", "invalid", "period", "invalid", "execution", "simple", "failure"]
Done

2022-03-08 12:48 UTC, merged